Maybe fixed delete empty collections
serpconnect/backend pull request #18
Opened 2016-09-28 08:25 UTC by Timbozand

Fixes #6

2016-09-28 08:51 UTC, smeets requested changes
Make a compound query instead of two separate (see removeEntry route)

2016-09-28 09:55 UTC, Timbozand commented
Need to delete entries with no relations.

2016-10-03 06:46 UTC, Timbozand commented
Fixed so entries with no collection gets deleted

2016-10-03 06:51 UTC, smeets requested changes

2016-10-03 06:51 UTC, murlocbrand commented on src/main/java/se/lth/cs/connect/routes/Collection.java
> +    private void removeEntriesWithNoCollection(RouteContext rc){
No need to provide a `RouteContext`?

2016-10-03 06:53 UTC, smeets approved these changes

2016-10-03 06:53 UTC, murlocbrand commented on src/main/java/se/lth/cs/connect/routes/Collection.java
> +    private void removeEntriesWithNoCollection(RouteContext rc){
Need it to access `rc.getLocal("db")` to perform queries.

2016-10-03 06:53 UTC, merged