Closes #46
serpconnect/backend pull request #54
Opened 2016-11-24 15:07 UTC by Timbozand

2016-11-24 15:13 UTC, smetz commented on src/main/java/se/lth/cs/connect/routes/Account.java
> +            System.out.println(message); //REMOVE
Yes

2016-11-24 15:13 UTC, smetz commented on src/main/java/se/lth/cs/connect/routes/Account.java
> +            if(!frontend.equals("http://localhost:8181")){ //Dont wan't to send mail to serpconnect@cs.lth.se when we are testing.
Find test cases that send mail and call `app.useMailClient(new MailBox());` or something before.

2016-11-24 15:16 UTC, smetz commented on src/main/java/se/lth/cs/connect/routes/Account.java
> +    				sendEmail("serpconnect@cs.lth.se", "SERP connect email registration", "The following email has registered to SERP-connect:\n\n" + email);
@emenlu do you read this email inbox?

2016-11-24 15:18 UTC, emenlu commented on src/main/java/se/lth/cs/connect/routes/Account.java
> +    				sendEmail("serpconnect@cs.lth.se", "SERP connect email registration", "The following email has registered to SERP-connect:\n\n" + email);
Yes

2016-11-24 15:23 UTC, smeets requested changes

2016-11-24 15:23 UTC, smetz commented on src/main/java/se/lth/cs/connect/routes/Account.java
> +    				sendEmail("serpconnect@cs.lth.se", "SERP connect email registration", "The following email has registered to SERP-connect:\n\n" + email);
@Timbozand email addr and body needs to be configurable in the application.properties and messages_en.properties filef

2016-11-24 16:11 UTC, smeets requested changes

2016-11-24 16:11 UTC, smetz commented on src/main/resources/conf/application.properties
> +neo4j.password = hej
This shit right here

2016-11-24 16:12 UTC, smeets approved these changes
Ok, looks good!

2016-11-24 16:14 UTC, merged

2016-11-28 15:44 UTC, smetz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notify administrator when new users sign up](https://trello.com/c/uFlPFWTN/65-notify-administrator-when-new-users-sign-up)